FileVersion = 1

[Project]
Name = "wslay-beef"
TargetType = "BeefLib"
StartupObject = "wslay_beef.Program"

[Configs.Debug.Win64]
OtherLinkFlags = "$(LinkFlags) ws2_32.lib winmm.lib"
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\wslay_d.lib"]

[Configs.Release.Win64]
OtherLinkFlags = "$(LinkFlags) ws2_32.lib winmm.lib"
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\wslay.lib"]
